server.port=8082
spring.application.name=inventory-service
# Config Server එකට සම්බන්ධ වීමට මේක අනිවාර්යයි
spring.config.import=optional:configserver:http://localhost:8888
# Database
spring.datasource.url=jdbc:mysql://localhost:3306/cosmic_inventory_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Ijse@123
# GCP Project ID (JSON එකේ තියෙන "project_id" එක මෙතනට දාන්න)
spring.cloud.gcp.project-id=cosmic-apparel-system-454512 

# JSON Key එක තියෙන තැන (Forward slashes පාවිච්චි කිරීම වඩාත් සුදුසුයි)
spring.cloud.gcp.credentials.location=file:/home/danithahk/cosmic-apparel-system-1d3d3308802d.json
# ඔයා හදපු Bucket එකේ නම
spring.cloud.gcp.storage.bucket=tiwling-designs-bucket
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Table එක නැත්නම් auto create වෙන්න මේක ඕනේ
spring.jpa.hibernate.ddl-auto=update

# SQL query එක console එකේ පේන්න මේකත් දාගන්න (optional)
spring.jpa.show-sql=true